name: ci
on:
  push:
    branches:
      - "**"
    paths-ignore:
      - 'README.md'

jobs:
  build_processrocket:
    name: build processrocket
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - run: echo "::remove-matcher owner=tsc::"
      - run: echo "::remove-matcher owner=eslint-compact::"
      - run: echo "::remove-matcher owner=eslint-stylish::"
      - uses: actions/cache@v2
        id: node_modules_cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-processrocket-${{ hashFiles('package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-processrocket-
      - run: node --version
      - run: npm --version
      - run: npm ci
      - uses: reviewdog/action-stylelint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          stylelint_input: '**/*.{css,scss,vue}'
          workdir: ./
      - uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          eslint_flags: './**/*.{vue,ts,js}'
          workdir: ./
      - run: npm run build
      - run: npm run test:unit
